### ISSUE TITLE
Conversation not rendering recommendations correctly

### ISSUE THREAD

**Issue by AaronStahley** [AaronStahley/SER401-BLSI#17]
When pressing yes nothing shows up but when pressing no it does. This also happens in reverse as well. When pressing no nothing shows up but when pressing yes it does. Not sure what the issue it but seems like whatever you press first nothing will show up it is only on the second click that it works. Seems to happen on both iOS and Android

**Comment by cagloria** [comment]
Same thing happens when selecting yes twice or no twice. You can also use the drop down menu to select any option that's not already selected and select any other option again to push the conversation forward without ever selecting yes or no. Tested on Android.
